### ISSUE TITLE
请问如何修改docker部署的mysql的密码

### ISSUE THREAD

**Issue by yuzebin** [ch3nnn/webstack-go#49]
你好，首先感谢你的辛勤工作，做出这个项目。
我在尝试能修改docker部署的mysql密码，修改后部署，但是在install之后，重启容器，webstack-go-service 无法启动，查看logs，提示是 Access denied for user 'root'@'192.168.80.4' (using password: YES)，如果还原为123456就可以正常工作。
请问该如何修改密码，谢谢。

**Comment by yuzebin** [comment]
补充一下：修改了两个文件：
docker-compose.yml
configs/docker-configs.toml

**Comment by ch3nnn** [comment]
> 补充一下：修改了两个文件： docker-compose.yml configs/docker-configs.toml

了解, 可以把具体修改地方粘出来。我自己试了是正常运行的, 部署前可以把之前创建的容器删掉重新部署。

configs/docker-configs.toml 修改 mysql.read 和  mysql.write  **pass** 字段
```
[mysql]

  [mysql.base]
    connmaxlifetime = 60
    maxidleconn = 60
    maxopenconn = 10

  [mysql.read]
    addr = "webstack-go-mysql:3306"
    name = "webstack-go"
    pass = "abc123123"
    user = "root"

  [mysql.write]
    addr = "webstack-go-mysql:3306"
    name = "webstack-go"
    pass = "abc123123"
    user = "root"

```

docker-compose.yml  修改  **MYSQL_ROOT_PASSWORD** 字段
```
  webstack-go-mysql:
    image: mysql/mysql-server:5.7
    container_name: webstack-go-mysql
    environment:
      MYSQL_DATABASE: webstack-go
      TZ: Asia/Shanghai
      # 允许来自其他主机的根连接
      # https://dev.mysql.com/doc/refman/5.7/en/docker-mysql-more-topics.html#docker_var_mysql-root-host
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: abc123123
    ports:
      - "3306:3306"
    networks:
      - webstack-go
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      <<: *healthcheck_defaults

```
